import { Product } from "@/lib/products";

/** Branded catalogue entries — pricing follows collection rules in products.ts */
export const catalogProducts: Product[] = [
  {
    slug: "louis-vuitton-pacific-chill",
    name: "Louis Vuitton - Pacific Chill",
    collection: "Louis Vuitton",
    family: "Oud", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-imagination",
    name: "Louis Vuitton - Imagination",
    collection: "Louis Vuitton",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-limmensite",
    name: "Louis Vuitton - L'Immensité",
    collection: "Louis Vuitton",
    family: "Woody", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-stellar-times",
    name: "Louis Vuitton - Stellar Times",
    collection: "Louis Vuitton",
    family: "Floral", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-ombre-nomade",
    name: "Louis Vuitton - Ombre Nomade",
    collection: "Louis Vuitton",
    family: "Citrus", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-orage",
    name: "Louis Vuitton - Orage",
    collection: "Louis Vuitton",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "louis-vuitton-afternoon-swim",
    name: "Louis Vuitton - Afternoon Swim",
    collection: "Louis Vuitton",
    family: "Musk", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 150, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "nasomatto-black-afghano",
    name: "Nasomatto - Black Afghano",
    collection: "Black Afghano",
    family: "Aquatic", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 200, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "mugler-angel",
    name: "Mugler - Angel",
    collection: "Women",
    family: "Oud", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-miss-dior",
    name: "Dior - Miss Dior",
    collection: "Women",
    family: "Sweet", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "xerjoff-erba-pura-accento",
    name: "Xerjoff - Erba Pura (Accento)",
    collection: "Women",
    family: "Woody", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "yves-saint-laurent-black-opium",
    name: "Yves Saint Laurent - Black Opium",
    collection: "Women",
    family: "Floral", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-because-its-you",
    name: "Giorgio Armani - Because It's You",
    collection: "Women",
    family: "Citrus", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "prada-paradoxe",
    name: "Prada - Paradoxe",
    collection: "Women",
    family: "Oriental", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-si",
    name: "Giorgio Armani - Si",
    collection: "Women",
    family: "Musk", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-jadore",
    name: "Dior - J'adore",
    collection: "Women",
    family: "Aquatic", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "mancera-coco-vanille",
    name: "Mancera - Coco Vanille",
    collection: "Women",
    family: "Oud", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "mancera-roses-vanille",
    name: "Mancera - Roses Vanille",
    collection: "Women",
    family: "Sweet", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "chanel-coco-mademoiselle",
    name: "Chanel - Coco Mademoiselle",
    collection: "Women",
    family: "Woody", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "britney-spears-fantasy",
    name: "Britney Spears - Fantasy",
    collection: "Women",
    family: "Floral", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "valentino-born-in-roma-women",
    name: "Valentino - Born In Roma (Women)",
    collection: "Women",
    family: "Citrus", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "thomas-kosmala-no-4",
    name: "Thomas Kosmala - No. 4",
    collection: "General",
    family: "Oriental", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "givenchy-gentleman",
    name: "Givenchy - Gentleman",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dolce-gabbana-the-one-mysterious-night",
    name: "Dolce & Gabbana - The One Mysterious Night",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "issey-miyake",
    name: "Issey Miyake",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "yves-saint-laurent-y",
    name: "Yves Saint Laurent - Y",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "xerjoff-alexandria-ii",
    name: "Xerjoff - Alexandria II",
    collection: "General",
    family: "Woody", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "yves-saint-laurent-babycat",
    name: "Yves Saint Laurent - Babycat",
    collection: "General",
    family: "Floral", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "vilhelm-parfumerie-vilhelmina",
    name: "Vilhelm Parfumerie - Vilhelmina",
    collection: "General",
    family: "Citrus", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "parfums-de-marly-delina",
    name: "Parfums de Marly - Delina",
    collection: "General",
    family: "Oriental", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "carolina-herrera-bad-boy",
    name: "Carolina Herrera - Bad Boy",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-acqua-di-gio",
    name: "Giorgio Armani - Acqua Di Gio",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-acqua-di-gio-profumo",
    name: "Giorgio Armani - Acqua Di Gio Profumo",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-code-profumo",
    name: "Giorgio Armani - Code Profumo",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-code",
    name: "Giorgio Armani - Code",
    collection: "General",
    family: "Woody", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "parfums-de-marly-kalan",
    name: "Parfums de Marly - Kalan",
    collection: "General",
    family: "Floral", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "parfums-de-marly-athair",
    name: "Parfums de Marly - Athair",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "parfums-de-marly-pegasus",
    name: "Parfums de Marly - Pegasus",
    collection: "General",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "parfums-de-marly-layton",
    name: "Parfums de Marly - Layton",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "amouage-purpose-50",
    name: "Amouage - Purpose 50",
    collection: "General",
    family: "Aquatic", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "amouage-opus-vii",
    name: "Amouage - Opus VII",
    collection: "General",
    family: "Oud", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "amouage-interlude",
    name: "Amouage - Interlude",
    collection: "General",
    family: "Sweet", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "lancome-oud-bouquet",
    name: "Lancôme - Oud Bouquet",
    collection: "General",
    family: "Woody", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-soleil-blanc",
    name: "Tom Ford - Soleil Blanc",
    collection: "General",
    family: "Floral", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-myrrhe-mystere",
    name: "Tom Ford - Myrrhe Mystère",
    collection: "General",
    family: "Citrus", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-tobacco-vanille",
    name: "Tom Ford - Tobacco Vanille",
    collection: "General",
    family: "Oriental", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-oud-wood",
    name: "Tom Ford - Oud Wood",
    collection: "General",
    family: "Musk", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-ombre-leather",
    name: "Tom Ford - Ombré Leather",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-black-orchid",
    name: "Tom Ford - Black Orchid",
    collection: "General",
    family: "Oud", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "tom-ford-noir",
    name: "Tom Ford - Noir",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "carolina-herrera-212-vip-black",
    name: "Carolina Herrera - 212 VIP Black",
    collection: "General",
    family: "Woody", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "hugo-boss",
    name: "Hugo Boss",
    collection: "General",
    family: "Floral", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "chanel-bleu-de-chanel",
    name: "Chanel - Bleu de Chanel",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "versace-eros",
    name: "Versace - Eros",
    collection: "General",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-sauvage-elixir",
    name: "Dior - Sauvage Elixir",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-sauvage",
    name: "Dior - Sauvage",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "creed-viking",
    name: "Creed - Viking",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "creed-aventus-absolu",
    name: "Creed - Aventus Absolu",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "creed-aventus",
    name: "Creed - Aventus",
    collection: "General",
    family: "Woody", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jean-paul-gaultier-le-male-elixir",
    name: "Jean Paul Gaultier - Le Male Elixir",
    collection: "General",
    family: "Floral", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jean-paul-gaultier-le-male-pride",
    name: "Jean Paul Gaultier - Le Male Pride",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jean-paul-gaultier-le-male",
    name: "Jean Paul Gaultier - Le Male",
    collection: "General",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "paco-rabanne-invictus-victory-elixir",
    name: "Paco Rabanne - Invictus Victory Elixir",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "paco-rabanne-invictus",
    name: "Paco Rabanne - Invictus",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "valentino-born-in-roma-green",
    name: "Valentino - Born In Roma (Green)",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "valentino-born-in-roma-uomo",
    name: "Valentino - Born In Roma Uomo",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jean-paul-gaultier-scandal",
    name: "Jean Paul Gaultier - Scandal",
    collection: "General",
    family: "Woody", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jean-paul-gaultier-scandal-absolu",
    name: "Jean Paul Gaultier - Scandal Absolu",
    collection: "General",
    family: "Floral", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-stronger-with-you",
    name: "Giorgio Armani - Stronger With You",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-stronger-with-you-intensely",
    name: "Giorgio Armani - Stronger With You Intensely",
    collection: "General",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "giorgio-armani-stronger-with-you-leather",
    name: "Giorgio Armani - Stronger With You Leather",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "lattafa-khamrah-qahwa",
    name: "Lattafa - Khamrah Qahwa",
    collection: "General",
    family: "Aquatic", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "lattafa-khamrah",
    name: "Lattafa - Khamrah",
    collection: "General",
    family: "Oud", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "rochas-moustache",
    name: "Rochas - Moustache",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "arabian-oud-resala",
    name: "Arabian Oud - Resala",
    collection: "General",
    family: "Woody", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "swiss-arabian-shaghaf",
    name: "Swiss Arabian - Shaghaf",
    collection: "General",
    family: "Floral", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "gucci-gucci-oud",
    name: "Gucci - Gucci Oud",
    collection: "General",
    family: "Citrus", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-oud-ispahan",
    name: "Dior - Oud Ispahan",
    collection: "General",
    family: "Oriental", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dior-homme-intense",
    name: "Dior - Homme Intense",
    collection: "General",
    family: "Musk", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dolce-gabbana-intense",
    name: "Dolce & Gabbana - Intense",
    collection: "General",
    family: "Aquatic", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dolce-gabbana-the-one",
    name: "Dolce & Gabbana - The One",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "mashaer",
    name: "Mashaer",
    collection: "General",
    family: "Sweet", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "initio-side-effect",
    name: "Initio - Side Effect",
    collection: "General",
    family: "Woody", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "nishane-ani",
    name: "Nishane - Ani",
    collection: "General",
    family: "Floral", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "nishane-hacivat",
    name: "Nishane - Hacivat",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "burberry-hero",
    name: "Burberry - Hero",
    collection: "General",
    family: "Oriental", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-marine-reign.png", accent: "#5e8ca0",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "ghoubar-al-thahab",
    name: "Ghoubar Al Thahab",
    collection: "General",
    family: "Musk", gender: "Unisex",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/hero.png", accent: "#c6a15b",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "burberry-her",
    name: "Burberry - Her",
    collection: "General",
    family: "Aquatic", gender: "For Her",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/atmosphere.png", accent: "#8a7a6a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "jacques-bogart-silver-scent",
    name: "Jacques Bogart - Silver Scent",
    collection: "General",
    family: "Oud", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-noir-oud.png", accent: "#b5854a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "viktor-rolf-spicebomb",
    name: "Viktor & Rolf - Spicebomb",
    collection: "General",
    family: "Sweet", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-rose-elixir.png", accent: "#c98a8a",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "versace-blue-jeans",
    name: "Versace - Blue Jeans",
    collection: "General",
    family: "Woody", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-citrus-aura.png", accent: "#cdab5e",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "dunhill-desire-red",
    name: "Dunhill - Desire Red",
    collection: "General",
    family: "Floral", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-amber-soul.png", accent: "#c47a35",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
  {
    slug: "paco-rabanne-one-million",
    name: "Paco Rabanne - One Million",
    collection: "General",
    family: "Citrus", gender: "For Him",
    tagline: "A signature composition, crafted with care.",
    description: "An exceptional fragrance from our curated collection. Available in 50ml and 100ml.",
    price: 120, image: "/images/p-velvet-musk.png", accent: "#b9a98c",
    notes: { top: ["Bergamot", "Citrus"], heart: ["Floral Accord", "Spice"], base: ["Musk", "Wood"] },
  },
];
